AWSTemplateFormatVersion: 2010-09-09
Description: Initializes account creation 
  
Parameters:
  LoggingAccountEmail:
    Description: Email address used to create a centralized logging account
    Type: String
    MinLength: 6
    MaxLength: 64 
    AllowedPattern: ^[_A-Za-z0-9-\+\.]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$
    ConstraintDescription: Account Email can contain only ASCII characters. This must be in the format of something@email.com
  DevAccountEmail:
    Description: Email address used create a dev environment account 
    Type: String
    MinLength: 6
    MaxLength: 64
    AllowedPattern: ^[_A-Za-z0-9-\+\.]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$
    ConstraintDescription: Account Email can contain only ASCII characters. This must be in the format of something@email.com
  StagingAccountEmail:
    Description: Email address used create a staging environment account 
    Type: String
    MinLength: 6
    MaxLength: 64
    AllowedPattern: ^[_A-Za-z0-9-\+\.]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$
    ConstraintDescription: Account Email can contain only ASCII characters. This must be in the format of something@email.com
  ProdAccountEmail:
    Description: Email address used create a prod environment account
    Type: String
    MinLength: 6
    MaxLength: 64
    AllowedPattern: ^[_A-Za-z0-9-\+\.]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$
    ConstraintDescription: Account Email can contain only ASCII characters. This must be in the format of something@email.com


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label: 
        default: Organization Security OU Configuration 
      Parameters:
      - LoggingAccountEmail
    - Label:
        default: Organization Workloads OU Configuration 
      Parameters:
      - DevAccountEmail
      - StagingAccountEmail
      - ProdAccountEmail
    
    ParameterLabels:
      LoggingAccountEmail:
        default: Log Archive Account Email Address
      DevAccountEmail:
        default: Dev Account Email Address
      StagingAccountEmail:
        default: Staging Account Email Address
      ProdAccountEmail:
        default: Prod Account Email Address
      

Resources:
  LambdaAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: CreateOrgsLambda
  
  LambdaOrgFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        S3Bucket: testing-org-lambda
        S3Key: createOrg.zip
      Handler: createOrg.lambda_handler
      Role: !GetAtt LambdaAdminRole.Arn
      Runtime: python3.6
      FunctionName: createOrg
      Timeout: 600


  TriggerOrgLambda:
    Type: "Custom::TriggerOrgLambda"
    Properties:
      ServiceToken: !GetAtt LambdaOrgFunction.Arn
      LoggingEmail: !Ref LoggingAccountEmail
      DevEmail: !Ref DevAccountEmail
      StagingEmail: !Ref StagingAccountEmail
      ProdEmail: !Ref ProdAccountEmail

  
# Outputs: