AWSTemplateFormatVersion: 2010-09-09
Description: Create SNS topic for slack chatbot & chatOps
  
Parameters:
  SlackWebHookUrl:
    Description: Incoming WebHooks Integration for slack channel messaging 
    Type: String


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Slack Channel Messaging Configuration 
      Parameters:
      - SlackWebHookUrl
    
    ParameterLabels:
      SlackWebHookUrl:
        default: Slack WebHook Url

  
Resources:
  SlackFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        S3Bucket: testing-org-lambda
        S3Key: slack.zip
      Handler: slack.lambda_handler
      Role: !ImportValue LambdaRole
      Runtime: python3.7
      FunctionName: slack
      Timeout: 30
  
  SlackTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !GetAtt SlackFunction.Arn
          Protocol: lambda

  SlackTopicPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SlackFunction.Arn
      Principal: sns.amazonaws.com
      SourceArn: !Ref SlackTopic

  OnFailureTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !GetAtt SlackFunction.Arn
          Protocol: lambda

  OnFailureTopicPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SlackFunction.Arn
      Principal: sns.amazonaws.com
      SourceArn: !Ref OnFailureTopic
  
  
Outputs:
  SlackTopicArn:
    Description: Success Topic Arn 
    Value: !Ref SlackTopic
  OnFailureArn:
    Description: Failure Topic Arn
    Value: !Ref  OnFailureTopic