AWSTemplateFormatVersion: 2010-09-09
Description: Template to create cloudtrail logs, IAM Role, and an encrypted storage bucket|
  
# Parameters:
  
Resources:
  # accountTrail:
  #   Type: "AWS::CloudTrail::Trail"
  #   Properties:
  #     EventSelectors:
  #       - DataResources:
  #         - Type: AWS::S3::Object
  #           Values:
  #             - !Sub arn:aws:s3:::${encryptedBucket}/
  #     EnableLogFileValidation: true
  #     IsLogging: true
  #     S3BucketName: !Ref cloudtrailBucket
  #     TrailName: !Sub ${AWS::AccountId}-trail-do-not-delete

  encryptedBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::AccountId}-storage-bucket
      # LoggingConfiguration:
      #   DestinationBucketName: !Sub ${AWS::AccountId}-logs-do-not-delete
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  encryptedBucketRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub ${AWS::AccountId}
            Action: sts:AssumeRole
      Description: Minimum privilege role, allowing read & write to s3 bucket
      MaxSessionDuration: 3600
      RoleName: LimitedS3User

  bucketRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: ListObjectsInBucket
            Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt encryptedBucket.Arn
          - Sid: ListBucketsInAccountInConsole
            Effect: Allow
            Action: s3:ListAllMyBuckets
            Resource: arn:aws:s3:::* 
          - Sid: AllowReadWrite
            Effect: Allow
            Action: 
            - s3:PutObject
            - s3:Getobject
            Resource: !Sub arn:aws:s3:::${encryptedBucket}/*
      PolicyName: s3UserAccess
      Roles:
        - !Ref encryptedBucketRole

  # lambdaTestRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument: 
  #       Version: "2012-10-17"
  #       Statement:
  #         - Sid: AllowAssumeRole
  #           Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     Description: Allow lambda to do live unit testing
  #     RoleName: resourceTester

  # lambdaTestPolicy:
  #   Type: "AWS::IAM::Policy"
  #   Properties:
  #     PolicyDocument: 
  #       Version: "2012-10-17"
  #       Statement:
  #         - Sid: testBuckets
  #           Effect: Allow
  #           Action: 
  #           - s3:GetBucketLogging
  #           - s3:GetEncryptionConfiguration
  #           Resource: 
  #           - !GetAtt cloudtrailBucket.Arn
  #           - !GetAtt encryptedBucket.Arn
  #         - Sid: testTrail
  #           Effect: Allow
  #           Action: 
  #           - cloudtrail:GetTrailStatus
  #           - cloudtrail:GetEventSelectors
  #           Resource: !GetAtt accountTrail.Arn  
  #         - Sid: testPolicy
  #           Effect: Allow
  #           Action: iam:SimulatePrincipalPolicy
  #           Resource: !GetAtt encryptedBucketRole.Arn
  #         - Sid: readCF
  #           Effect: Allow
  #           Action: cloudformation:DescribeStacks
  #           Resource: '*'
  #     PolicyName: testAccess
  #     Roles:
  #       - !Ref lambdaTestRole

Outputs: 
  storageBucket:
    Description: name for storage bucket
    Value: !Ref encryptedBucket
  s3Role:
    Description: arn for s3 role
    Value: !GetAtt encryptedBucketRole.Arn
