AWSTemplateFormatVersion: 2010-09-09
Description: Template to create an centralized logging bucket, 
  
# Parameters:
  
Resources:
  cloudtrailBucket:
    DeletionPolicy: Retain 
    UpdateReplacePolicy: Retain 
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::AccountId}-logs-do-not-delete
      LoggingConfiguration:
        DestinationBucketName: !Sub ${AWS::AccountId}-logs-do-not-delete

  cloudtrailBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref cloudtrailBucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${cloudtrailBucket}
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${cloudtrailBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: 'bucket-owner-full-control'

Outputs:
  LoggingBucketName: 
    Description: Centralized logging bucket
    Value: !Ref cloudtrailBucket

