AWSTemplateFormatVersion: 2010-09-09
Description: Resources needed to run stackset.py
  
Resources:
  StacksetFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        S3Bucket: testing-org-lambda
        S3Key: stackset.zip
      Handler: stackset.lambda_handler
      Role: !ImportValue LambdaRole
      Runtime: python3.7
      FunctionName: stackset
      Timeout: 30  

  FourthQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      ContentBasedDeduplication: false
      FifoQueue: true
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadletterTargetArn: !ImportValue DeadLetterQueue
        maxReceiveCount: 5
      VisibilityTimeout: 150

  TriggerFourthFunction:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt FourthQueue.Arn
      FunctionName: !Ref StacksetFunction