AWSTemplateFormatVersion: 2010-09-09
Description: Resources needed to run unitTest.py
  
Resources:
  UnitTestFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        S3Bucket: testing-org-lambda
        S3Key: unitTest.zip
      Handler: unitTest.lambda_handler
      Role: !ImportValue LambdaRole
      Runtime: python3.7
      FunctionName: unitTest
      Timeout: 30

  FifthQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      ContentBasedDeduplication: false
      FifoQueue: true
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadletterTargetArn: !ImportValue DeadLetterQueue
        maxReceiveCount: 5
      VisibilityTimeout: 150

  TriggerFifthFunction:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      EventSourceArn: !GetAtt FifthQueue.Arn
      FunctionName: !Ref UnitTestFunction

  UnitTestDestinations:
    Type: "AWS::Lambda::EventInvokeConfig"
    Properties:
      FunctionName: !Ref UnitTestFunction
      MaximumRetryAttempts: 0
      MaximumEventAgeInSeconds: 60
      DestinationConfig:
        OnSuccess:
          Destination: !ImportValue SlackTopic
        OnFailure:
          Destination: !ImportValue OnFailureTopic
      Qualifier: '$LATEST'