AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Resources to run security experiments

Globals:
  Function:
    Runtime: python3.7
    MemorySize: 512
    Timeout: 30
  
  
Resources:
##########################################################################
#  accountInventory Function                                             #
##########################################################################

  accountInventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accountInventory
      CodeUri: lambdas/accountInventory
      Handler: accountInventory.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-pandas:22
      Policies:
        - Version: '2012-10-17'
          Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - s3:PutObject
              - organizations:ListAccounts

