AWSTemplateFormatVersion: 2010-09-09
Description: Template to create cloudtrail logs, IAM Role, and an encrypted storage bucket|
  
# Parameters:
  
Resources:
  encryptedBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${AWS::AccountId}-storage-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  encryptedBucketRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub ${AWS::AccountId}
            Action: sts:AssumeRole
      Description: Minimum privilege role, allowing read & write to s3 bucket
      MaxSessionDuration: 3600
      RoleName: LimitedS3User

  bucketRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: ListObjectsInBucket
            Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt encryptedBucket.Arn
          - Sid: ListBucketsInAccountInConsole
            Effect: Allow
            Action: s3:ListAllMyBuckets
            Resource: arn:aws:s3:::* 
          - Sid: AllowReadWrite
            Effect: Allow
            Action: 
            - s3:PutObject
            - s3:Getobject
            Resource: !Sub arn:aws:s3:::${encryptedBucket}/*
      PolicyName: s3UserAccess
      Roles:
        - !Ref encryptedBucketRole

Outputs: 
  storageBucket:
    Description: name for storage bucket
    Value: !Ref encryptedBucket
  s3Role:
    Description: arn for s3 role
    Value: !GetAtt encryptedBucketRole.Arn
